services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - '11434:11434'
        volumes:
            - ollama:/root/.ollama
        environment:
            - OLLAMA_HOST=0.0.0.0
            - OLLAMA_ORIGINS=*
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        restart: unless-stopped

    piper-http:
        build:
            context: ./
            dockerfile: piper-http.Dockerfile
        container_name: piper-http
        ports:
            - '5001:5000'
        restart: unless-stopped

    # Nginx proxies requests to the Piper HTTP service.
    # Needed to handle CORS issues with the browser.
    nginx:
        image: nginx:alpine
        container_name: nginx-piper-proxy
        ports:
            - '5000:80'
        volumes:
            - ./nginx-piper.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - piper-http
        restart: unless-stopped

volumes:
    ollama:
