services:
    ollama:
        image: ollama/ollama
        container_name: ollama
        ports:
            - '11434:11434'
        volumes:
            - ollama:/root/.ollama
        environment:
            - OLLAMA_HOST=0.0.0.0
            - OLLAMA_ORIGINS=*
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [gpu]
        restart: unless-stopped

    piper-http:
        build:
            context: ./
            dockerfile: piper-http.Dockerfile
        container_name: piper-http
        ports:
            - '5000:5000'
        restart: unless-stopped

volumes:
    ollama:
